import React from 'react'
import Head from 'next/head'
import { Menu } from './Menu'

export const Layout = ({ children }: { children: any}) => {
  return (
    <>
      <Head>
        <title>Workout Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main>
        {children}
      </main>
    </>
  )
}
